### ISSUE TITLE
Lync Logger 1.2 with Skype For Business 2015 Doesn't Activate

### ISSUE THREAD

**Issue by steveswing** [Zougi/LyncLogger#1]
I just upgraded to Skype For Business 2015 and I'm unable to get Lync Logger to activate. Should it be able to login? I see a "Sign-in Logs" context menu entry from the Skype for Business tray icon. Does that come from Lync Logger? When I choose it a "Skype for Business Sign-in Logs" dialog displays a message "No sign-in data available." Is there a way to manually configure login information for Lync Logger? Do I have a different issue?

**Comment by fredericrous** [comment]
Yes LyncLogger should be able to login, the Lync 2013 sdk used by LyncLogger is working with Skype For Business 2015. Actually from the About window accessible from the Help menu of Skype for Business 2015, on my screen, I see on the first line `Microsoft Lync 2013 (15.0.4809.1000)`. You should see the same thing!? Skype for Business is a quick and dirty rebranding.
No, the `Sing-In Logs` in the context menu does not come from LyncLogger. LyncLogger does not alter Skype for Business/Lync. It just listens on events (do a conversation started, has a message been received, ...).I get the same message "No sign-in data available." when I click `Sign-in Logs` (with LyncLogger off). This message seems weird but 'normal'
No there is no way to configure LyncLogger to login manually without further development (pull requests are welcome)

There's a file LyncLogger.log created in the same folder as LyncLogger.exe that might give you some info!?

**Comment by steveswing** [comment]
I'm happy to report that running Repair from Control Panel -> Programs and Features -> Microsoft Office Professional Plus 2013 (change menu) fixed LyncLogger for me. Closing this issue. Thanks.
